### PR TITLE
API code base for HTTP_200.

### PR DESCRIPTION
**Pull request by dhruvhacks**
@RishabhJain2018 
Sir,
As discussed earlier, I've merged your code with the current ```master```.
This has been tested and everything works fine.

Please review :slightly_smiling_face:

### CODE REVIEW

**Comment by RishabhJain2018** [comment]
@dhruvhacks Can you please fix the travis build?

**Comment by dhruvhacks** [comment]
@RishabhJain2018 
Sure sir! Working on it!

**Comment by dhruvhacks** [comment]
@RishabhJain2018 Please review!

**Comment by RishabhJain2018** [comment]
@dhruvhacks **This is a really big change** & did you test it thoroughly on your local as well as on the server?

**Comment by dhruvhacks** [comment]
@RishabhJain2018 Sorry sir for the late response, We were busy rechecking this branch on staging server and everything works perfect! :slightly_smiling_face:

**Pull request merged**
